### ISSUE TITLE
Unmanaged exception: if program is in C:/Program Files (x86)/ and you run it for the first time, you will face "Access Denied" error

### ISSUE THREAD

**Issue by dag7dev** [amakvana/YuzuModDownloader#11]
**Describe the bug**
If program is in C:/Program Files (x86)/<dirname> and you run it for the first time, you will face "Access Denied" error

**To Reproduce**
1. make a new folder in the default install folder
2. run yuzumoddownloader
3. click on "download yuzu game mods"
4. unmanaged exception will prompt

**Expected behavior**
The program should refuse to run, if it doesn't have required permissions on its folder.

However, a nicer solution should be found (e.g. saving everything in %appdata%)

**Desktop/Laptop (please complete the following information):**
 - OS: Windows 10

**Comment by dag7dev** [comment]
`Extract contents of the YuzuModDownloader.zip file into your Yuzu root folder`

Didn't read this.

However, the exception is still there, it would be nice to have that exception managed anyway!

**Comment by amakvana** [comment]
I will look into handling the exceptions better, displaying user friendly messages. That was thrown because the program was placed inside a folder that doesn't grant write permissions without elevating.

Usually Emulators in general are advised against being stored inside `%programfiles%` or `%programfiles(x86)%` due to needing write permissions

**Comment by dag7dev** [comment]
> I will look into handling the exceptions better, displaying user friendly messages. That was thrown because the program was placed inside a folder that doesn't grant write permissions without elevating.

I think this could be helpful in any way: https://stackoverflow.com/questions/21755835/check-if-path-is-in-program-files
