### ISSUE TITLE
New Version: IO Exception -> dumps

### ISSUE THREAD

**Issue by frank196612** [amakvana/YuzuModDownloader#13]
**Describe the bug**

**To Reproduce**
1. Open Downlaoder
2. Click on 'Download Yuzu Game Modes'
4. Error Unhandled exception has accured: 
Details: 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
YuzuModDownloader
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///E:/Emulators/Yuzu/YuzuModDownloader.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Expected behavior**
Mods are being downloader, worked in the previuos version

**Screenshots**

**Desktop/Laptop (please complete the following information):**
 - OS: Windows 11
 - Yuzu Version Mainlane 998

**Comment by frank196612** [comment]
Sure I did everything worked fine until the last version, I am on aportable install. New version crashes for me. 
Thanks for looking at this.

**Comment by amakvana** [comment]
I've downloaded the latest copy of Yuzu Portable along with YMD, imported my games and ran YMD but can't reproduce the error. Are you able to provide the following for me?

1. Full Path to Yuzu Install
2. Games imported (including Title ID's)
3. Path to "Mod Load Root" - this can be found by opening Yuzu > Emulation > Configure > System > Filesystem.

**Comment by frank196612** [comment]
So I did some testing, reinstall etc. Same issue, same problem. Let me come back to your points. 

1.) E:\LaunchBox\Emulators\YuzuT  all config config files are under E:\LaunchBox\Emulators\YuzuT\User
3.)  E:\LaunchBox\Emulators\YuzuT\user\load
2) For testing I have only included the one XENO Blade game: Xenoblade Chronicles 2 (WLD).xci 0100E95004038000, however same thing happens for other games


As mentioned the last version did not crash. As I am running on Win11, maybe that could be the issue. I checked .Net etc. 

Thanks for your support!

**Comment by frank196612** [comment]
Hmmm, I deleted all yuzu files in Appdata to no avail; I will try a new yuzu install outside launchbox; 
Also everything was set-up as admin. The previous version worked, is this still available? I would revert back to find out, if this older version still works.

**Comment by amakvana** [comment]
> I will try a new yuzu install outside launchbox

Try this and let me know how you get on with this. If this works fine, it must be permissions on within your directories

> The previous version worked, is this still available? 

I'll have to recompile the binaries as it checks against GitHub for versioning, I'll do this soon and send you a copy within here

**Comment by frank196612** [comment]
Good afternoon, I belief you are right. I did a complete roll-back and reinstalled yuzu. Currently I can confirm your installer is running without breaking. 

Sorry for bringing this up and I really appreciate your support.

**Comment by amakvana** [comment]
> Sorry for bringing this up and I really appreciate your support.

No worries, anytime! Thanks for letting me know.
