### ISSUE TITLE
No mods downloaded to destination folder

### ISSUE THREAD

**Issue by goedzo** [amakvana/YuzuModDownloader#14]
I've updated to the latest version and now the naming bug is gone :). However it says it has downloaded 1245 mods (of 7589 games), but the custom load folder does not contain any downloaded mod or content. 

Note that I use yuzu in portable mode, so I have a user folder INSIDE the yuzu folder. It looks in the correct folder, because it detects all the game ID's, however it doesn't download any file. My yuzu setup is on an external USB disk.

Hope this helps.

**Comment by goedzo** [comment]
I tried to run it several times (without deleting the files) also in administrator modus. I was able to download about 10 mods and 10 zip files were saved. However it said it has downloaded 1245 mods, I didn't see them at all.

I did notice that I have triggered a rate limit on github, so it appears the app is trying to download too much?

**Comment by amakvana** [comment]
Can't seem to replicate it. I've tried it again and all the mods have downloaded fine for my game dumps. 

The only thing I could possibly think of is that there could be the default yuzu folder structured also stored on your machine. As you've got the `user` folder set up, try the following:

1. Close Yuzu and YuzuModDownloader
2. Start > cmd 
3. Type the following command then press Enter: `rd /s /q "%localappdata%\yuzu"`
4. Type the following command then press Enter: `rd /s /q "%appdata%\yuzu"`
5. Close cmd
6. Open Yuzu.exe and confirm game paths are still set. 
7. Close Yuzu
8. Open YuzuModDownloader and run it  

What happens now?

**Comment by amakvana** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. 

Please reach out if you have or find the answers we need so that we can investigate further.
