### ISSUE TITLE
An attempt was made to move the file pointer before the file

### ISSUE THREAD

**Issue by waxp69** [amakvana/YuzuModDownloader#16]
![Screenshot 2022-08-08 223538](https://user-images.githubusercontent.com/110874855/183554127-1776cb42-e9ee-4b00-a368-101a8e79659c.png)

**Comment by amakvana** [comment]
Thanks for opening this! Are you able to provide me a couple of things please :)

- Full path to yuzu.exe
- Full path to Mod Load Root (this can be found in yuzu.exe > Emulation > Configure > System > Filesystem)
- Full path to YuzuModDownloader.exe
- All games within your Yuzu Library - so I can see which mods are being downloaded

Can you also run the program again. When the error pops up, click on the `Details` button and copy/paste the errors within there?

**Comment by fieldkim** [comment]
I'm not the reporter. But I have exactly same message. so I report it in my case :)
(but debug messages in Korean. Sorry :( )

* Full path to yuzu.exe : D:\Emulators\nsw\yuzu\yuzu-windows-msvc
* Full path to Mod Load Root : D:\Emulators\nsw\yuzu\yuzu-windows-msvc\load
* All games within your Yuzu Library
 * Bayonetta 2
 * Mega Max X Legacy Collection
 * The Ninja Saviors Return of the warriors
 * Super Mario Odyssey
 * Xenoblade Chronicles 3
 * Xenoblade Chronicles: Definitive Edition

`이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.IO.IOException: 파일 시작 앞으로 파일 포인터를 이동하려고 했습니다.

   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   위치: System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   위치: System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()


************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4515.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
YuzuModDownloader
    어셈블리 버전: 1.1.0.0
    Win32 버전: 1.1.0.0
    코드베이스: file:///D:/Emulators/nsw/yuzu/yuzu-windows-msvc/YuzuModDownloader.exe
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4515.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4488.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4395.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4341.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4515.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.resources.dll
----------------------------------------
System.IO.Compression.FileSystem
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.IO.Compression.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.IO.Compression.resources.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4161.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.


`

**Comment by amakvana** [comment]
Thanks for this @fieldkim , can you also send me the full path from where you run YuzuModDownloader.exe from?

I will look into this as soon as possible and troubleshoot!

**Comment by amakvana** [comment]
@fieldkim can you also tell me if you have the following directory created?

`D:\Emulators\nsw\yuzu\yuzu-windows-msvc\7z` 

If so, what is inside the directory?

**Comment by fieldkim** [comment]
Nope. no 7z folder.

**Comment by fieldkim** [comment]
.......and YuzuModDownloader.exe ran on 
D:\Emulators\nsw\yuzu\yuzu-windows-msvc
directory

**Comment by amakvana** [comment]
Usually the `load` folder is populated inside the `User` folder if Yuzu is set up as a standalone version. Can you take a screenshot of the entire directory structure where yuzu.exe resides? @fieldkim, sorry for the specific questions.

**Comment by fieldkim** [comment]
![image](https://user-images.githubusercontent.com/20085316/183786839-88329a34-78e4-48e9-a8af-107d35f2ef7b.png)

it won't source of the problem. I changed load folder from default (in user folder) to that (in sub folder), after I got same exception error. (yes. in default setting, i got same exception error)

**Comment by amakvana** [comment]
@fieldkim I haven't forgotten about this. Thanks for getting back to me! Can you confirm if the following directory exists on your PC. Hold the Windows Key + R down, in the Run prompt, enter the following below:

`%appdata%\yuzu`

If a folder launches, can you take a screenshot of the entire folder structure for me please

**Comment by fieldkim** [comment]
![image](https://user-images.githubusercontent.com/20085316/184599353-d79fd6c5-88f1-4fb2-bc48-7cdc78bfe2a4.png)

**Comment by amakvana** [comment]
@fieldkim thanks! Can you also take a screenshot of the `7z` folder and the `load` folder?

**Comment by fieldkim** [comment]
![image](https://user-images.githubusercontent.com/20085316/184602919-2430f578-fabd-41bd-beae-15230f9e1a21.png)
![image](https://user-images.githubusercontent.com/20085316/184602975-8cacc3a8-a387-4421-ab69-f0b6cd87ae64.png)

**Comment by fieldkim** [comment]
Oh, after deleting contents in load folder, Exception error gone!
huh.

**Comment by amakvana** [comment]
Can you delete the `7z` folder, also consider deleting the contents of the `load` folder too;. Rerun the application and see if the exception goes away

**Comment by fieldkim** [comment]
I did, and yes. Exception errors went away.

**Comment by amakvana** [comment]
Can you just screenshot me the `7z` folder again now that the exception errors have gone. Also, can you confirm the mods successfully downloaded for your games?

**Comment by amakvana** [comment]
@waxp69 try running the following commands in Command Prompt, then rerunning YuzuModDownloader again. 

1. Start > Command Prompt 
2. Copy & Paste the two commands below into Command Prompt, pressing `Enter` after typing each one:
```
rmdir /s /q "%appdata%\yuzu\7z"
rmdir /s /q "%appdata%\yuzu\load"
```
3. Rerun YuzuModDownloader and see if the errors persist

**Comment by fieldkim** [comment]
![image](https://user-images.githubusercontent.com/20085316/184630690-6ba93b6b-cdc8-48d9-85e1-e752a4b4baba.png)
And yes. mods are successfully downloaded and could be enabled. thanks.:)

**Comment by amakvana** [comment]
Thanks for confirming this @fieldkim 

@waxp69 are you able to confirm the problem is resolved if you follow the steps in this [reply](https://github.com/amakvana/YuzuModDownloader/issues/16#issuecomment-1214819231)

**Comment by waxp69** [comment]
> @waxp69 try running the following:
> 
> 1. Start > Command Prompt
> 2. Copy & Paste the commands below into Command Prompt, pressing `Enter` after typing each one:
> 
> ```
> rd /s /q "%appdata%\yuzu\7z"
> rd /s /q "%appdata%\yuzu\load"
> md "%appdata%\yuzu\load"
> ```
> 
> 3. Rerun YuzuModDownloader and see if the errors persist

I do not have 7z

**Comment by amakvana** [comment]
> I do not have 7z

Are you able to provide me a couple of things please

- Full path to yuzu.exe
- Full path to `Mod Load Root` (this can be found in yuzu.exe > Emulation > Configure > System > Filesystem)
- Full path to YuzuModDownloader.exe
- Folder structure of `%appdata%\yuzu`
- All games within your Yuzu Library - so I can see which mods are being downloaded

Can you also run the program again. When the error pops up, click on the `Details` button and copy/paste the errors within there into here.

**Comment by waxp69** [comment]
yuzu: C:\Users\moham\AppData\Roaming\yuzu
Mod downloader: C:\Users\moham\AppData\Local\yuzu\yuzu-windows-msvc
![yuzu folder](https://user-images.githubusercontent.com/110874855/184724607-21e8fae4-a97c-43ea-9a2a-59198ac688a1.png)
![yuzu games](https://user-images.githubusercontent.com/110874855/184724626-c0a45adb-a2cc-49a1-a7ba-ff6ba0d10ca6.png)

**Comment by amakvana** [comment]
Thanks for that! Can you also show me the path to `Mod Load Root`, this can be found in yuzu.exe > Emulation > Configure > System > Filesystem.

Also, can you also run the program again. When the error pops up, click on the `Details` button and copy/paste the errors within there into here.

**Comment by waxp69** [comment]
oh wow, it works now for whatever reason

**Comment by amakvana** [comment]
> oh wow, it works now for whatever reason

Okay good! Can you confirm mods are being downloaded?

**Comment by waxp69** [comment]
they are
