### ISSUE TITLE
"Unhandled exception has occurred" 

### ISSUE THREAD

**Issue by saoghalqc** [amakvana/YuzuModDownloader#22]
**Describe the bug**

**To Reproduce**
Whenever I open the ModDownloader (it's located in the main yuzu.exe file location like it should)

**Expected behavior**

**Screenshots**
[
![image_2022-12-26_202802672](https://user-images.githubusercontent.com/115330220/209596930-91050bf3-df3d-4757-a47d-10ba442a03fb.png)
](url)

**Desktop/Laptop (please complete the following information):**
 - OS:  Windows 11
 - Yuzu Version: Mainline 1284
 - Yuzu Standalone or Installed? Installed
 

**Additional context**
None.

**Comment by amakvana** [comment]
_Could not load file or assembly "HtmlAgilityPack"_ means the `HtmlAgilityPack.dll` file is missing.

When you extract the `YuzuModDownloader.zip` archive, you need to make sure you **also** move the `HtmlAgilityPack.dll` file into the same directory `YuzuModDownloader.exe` is placed in.

**Comment by saoghalqc** [comment]
I didn't see that file in the first place, I don't know why! Well, that works now, thanks!
