### ISSUE TITLE
Bayonetta 3 not included from theBoy181 Github

### ISSUE THREAD

**Issue by PhynixAbyss** [amakvana/YuzuModDownloader#23]
**Describe the bug**
Bayonetta 3 Mods are not downloaded after downloading from theBoy181 Github, but its on his Github available to download.

**To Reproduce**
1. Have YuzuModDownloader open
2. Switch to theBoy181 Github and press Download
3. ...
4. No Bayonetta 3 Mods even if they are available on his Github

**Expected behavior**
Downloads all Mods for every installed Game (Does not).

**Desktop/Laptop (please complete the following information):**
 - OS: Windows 10
 - Yuzu Version: 1327
 - Yuzu Standalone or Installed? (What?) Just downloaded from the Website
 - Game Title: Bayonetta 3 (Probably more Games)
 - Game Title ID: 0x010076F0049A2000

**Comment by amakvana** [comment]
Looks like the copy you have (010076F0049A2000) isn't the same as the copy which has been uploaded onto theboy181's repo. The one on his repo has the Game Title ID of: 01004A4010FEA000.

**Comment by PhynixAbyss** [comment]
Yes it is 01004A4010FEA000, i apparently have sent the Title ID from Bayonetta 1, i am sorry.

**Comment by amakvana** [comment]
> Yes it is 01004A4010FEA000, i apparently have sent the Title ID from Bayonetta 1, i am sorry.
> 
> I am from Europe.
> 
> I was able to download them manually and they do also work, so thats why i thought i should maybe ask if i did something wrong or the Downloader does just not work correctly.
> 
> I also use custom paths, idk if thats a Problem, it detected most Games tho, so that should not be the Case.

Let me try it on mine as I too have Bayonetta 3. What version is your game on?

**Comment by amakvana** [comment]
I've just tried it on my copy, v1.1.0 and Title ID: 01004A4010FEA000, all 3 have downloaded fine.

**Comment by PhynixAbyss** [comment]
Oh, okay i have Version Update 1.2.0, that would explain it.

Wonder if it still would make sense, if it still lets me download it tho, but i am not sure.

Well, thanks for trying it out!

**Comment by amakvana** [comment]
For theboy181's repo, it will only download mods if the version and title ID match, due to how their repo is setup. 

You could test the mods by manually downloading them and see if they work on 1.2.0. If they do, open an Issue on theboy181's repo and let them know so they can then add 1.2.0 compatible mods

**Comment by PhynixAbyss** [comment]
Okay, that is kinda sad, thanks for helping out!

**Comment by amakvana** [comment]
@PhynixAbyss - just a heads up, theboy181 has released 1.2.0 mods for Bayonetta 3. They should pull down with YuzuModDownloader if you try it again now
