### ISSUE TITLE
Font error on steamdeck even if installed ttf-ms-fonts

### ISSUE THREAD

**Issue by prosup** [amakvana/YuzuModDownloader#26]
**Describe the bug**
As the topic:Font error on steamdeck even if installed ttf-ms-fonts
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl) in /_/src/Avalonia.Base/Media/FontManager.cs:line 37

**To Reproduce**
run the program in terminal,allways reproduce the error

**Expected behavior**
-

**Screenshots**
-

**Desktop/Laptop (please complete the following information):**
 - OS: [steamdeck os]
 - Yuzu Version [rolling version installed with yay -Sy yuzu-early-access-appimage]

**Comment by amakvana** [comment]
Apologies for the delayed reply! Looks like this is an issue with Avalonia itself, see: 
https://github.com/AvaloniaUI/Avalonia/issues/4427

Try some of the fixes suggested there and let me know the outcome.

**Comment by amakvana** [comment]
Closed - Fixed in v1.4.1.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
