### ISSUE TITLE
Mods not downloading

### ISSUE THREAD

**Issue by BeardedJellyfish** [amakvana/YuzuModDownloader#28]
the mod manager is not putting the mods in the correct folders to be used - the application properly scans the emulator for games and shows it trying to download the mods - I get the "games for 8 mods downloaded" but there's nothing anywhere on my system

the mod manager worked flawlessly in the past - I stopped using Yuzu for a number of months because it wouldn't function in any capacity

**Screenshots**

**Desktop/Laptop (please complete the following information):**
windows 11
Yuzu 1540 - installed
games Bayonetta 3, origami king, forgotton land, new pokemon snap, link's awakening, breath of the wild, tears of the kingdom and mario odyssey

**Comment by amakvana** [comment]
Thanks for opening up the issue!

Could you attach your qt-config.ini file here for me to have a look at?

Cheers!



On 28 Aug 2023, at 17:51, BeardedJellyfish ***@***.***> wrote:

﻿

Assigned #28<https://github.com/amakvana/YuzuModDownloader/issues/28> to @amakvana<https://github.com/amakvana>.

**Comment by amakvana** [comment]
Closed - Fixed in v1.4.1.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
