### ISSUE TITLE
Question, when I extract the zip and look in the folder, I can't find the exe file, where is it?

### ISSUE THREAD

**Issue by amakvana** [amakvana/YuzuModDownloader#3]
Question, when I extract the zip and look in the folder, I can't find the exe file, where is it?

_Originally posted by @EL86 in https://github.com/amakvana/YuzuModDownloader/issues/2#issuecomment-887582301_

**Comment by amakvana** [comment]
Download it from the URL below:
https://github.com/amakvana/YuzuModDownloader/releases/latest

Double-click on YuzuModDownloader.zip, not Source.zip

**Comment by EL86** [comment]
> Download it from the URL below:
> https://github.com/amakvana/YuzuModDownloader/releases/latest
> 
> Double-click on YuzuModDownloader.zip, not Source.zip

Thanks, I see it now
