### ISSUE TITLE
Show game titles in confirmation dialog

### ISSUE THREAD

**Issue by kathyrollo** [amakvana/YuzuModDownloader#36]
**Is your feature request related to a problem? Please describe.**
If you have many games, it is difficult to know which games got new mods downloaded for.

**Describe the solution you'd like**
Please also include a list of updated games in this dialog:

![Screenshot 2024-01-17 180826](https://github.com/amakvana/YuzuModDownloader/assets/28589393/7466cec4-ceaa-45c2-baeb-ad900e564b84)

You don't really know what is that 1 game.

**Describe alternatives you've considered**
Manually looking under the Add-Ons column in the games list.

**Additional context**
The above workaround is tedious when you have 50 games for example.

**Comment by amakvana** [comment]
Hi @kathyrollo 

Have a look at the test build below. Drop the executable inside the same folder `yuzu.exe` resides, then run it.

Upon the successful mod downloading confirmation window appearing, click on "Show Details" to see the games which mods have been downloaded for.

Does this achieve what you wanted? Let me know! 

Cheers! 

[YuzuModDownloader_1.4.1.0_Windows_Test_Build.zip](https://github.com/amakvana/YuzuModDownloader/files/14099949/YuzuModDownloader_1.4.1.0_Windows_Test_Build.zip)

**Comment by kathyrollo** [comment]
Hi @amakvana , just in time! I was updating my Switch collection and remembered to dropped by to see how this request came along.

![Screenshot 2024-02-03 102056](https://github.com/amakvana/YuzuModDownloader/assets/28589393/f7485fd9-929d-4ffb-b25c-b699dd0db74d)

Thank you, it's perfect!

**Comment by amakvana** [comment]
Closed - Added in v1.4.1.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
