### ISSUE TITLE
Downloader crashes when unpacking for Shin Megami Tensei V

### ISSUE THREAD

**Issue by brolio** [amakvana/YuzuModDownloader#37]
**Describe the bug**
When downloading from the official switch mods repo the app gets stuck for a couple of seconds on unpacking the file Config_SMTV_1080p.zip and then closes itself with no further message

**To Reproduce**
1. open the downloader
2. select the official mod repo
3. click download mods
4. wait
5. crash

**Expected behavior**
It should complete the download and give a recap message at the end of it

**Screenshots**
![immagine](https://github.com/amakvana/YuzuModDownloader/assets/32934191/69df6106-00d0-47a7-a17f-aa46b36428f8)
![immagine](https://github.com/amakvana/YuzuModDownloader/assets/32934191/bfe1c62c-f103-4e65-978e-9c0dd94724ab)
![immagine](https://github.com/amakvana/YuzuModDownloader/assets/32934191/29772573-8de9-40a9-b8b1-b330b3596abf)

**Desktop (please complete the following information):**
 - Windows 11
 - Yuzu Version EA 4137
 - Yuzu Standalone or Installed? portable install
 - Game Title Shin Megami Tensei V
 - Game Title ID 010063B012DC6000

**Additional context**
at first i thought it was caused by a "mismatch" in game versions since the last patch for it is 1.0.2 while the wiki i think it lists only up to 1.0.1, but i tried uninstalling the update alltogether and the problem persists, though as you can see in the second and third screenshots it seems like it's able to download and actually unpack something before crashing

**Comment by amakvana** [comment]
Thanks for opening up the issue! 

It looks some of the Mediafire links are timing out. I'll need to amend the code to handle this. 

Once done, I'll post a test build in here for you to confirm if it works fine on your end

Cheers!

**Comment by amakvana** [comment]
Hi @brolio,

Please can you download the test build attached and see if the issue persists - same instructions as usual.

There are a few performance optimisations too so it should feel snappier.

Cheers!

[YMD_1.4.2.0_Test_Build_winx64.zip](https://github.com/amakvana/YuzuModDownloader/files/14303434/YMD_1.4.2.0_Test_Build_winx64.zip)

**Comment by brolio** [comment]
Hi, probably a dumb question, but windows defender immediately blocks it as soon as i try to open the .zip archive, is it expected behaviour since it's a test build?

**Comment by amakvana** [comment]
> Hi, probably a dumb question, but windows defender immediately blocks it as soon as i try to open the .zip archive, is it expected behaviour since it's a test build?
> 
> EDIT: added screenshot, sorry it's in italian

No worries, you're correct. I haven't submitted it to Microsoft as its a test build. 

The final release will be submitted to Microsoft so this issue won't occur. For now, add an exception then test.

**Comment by amakvana** [comment]
> Seems to work like a charm now! 
> 
> Keep up the great work!

Thanks for confirming! I will push the changes out over the weekend

**Comment by amakvana** [comment]
Closed - Fixed in v1.4.2.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
