### ISSUE TITLE
Mods are not shown in Ryujinx portable

### ISSUE THREAD

**Issue by petran79** [amakvana/YuzuModDownloader#45]
While Yuzu mods register fine, Ryujinx does not display any mods when I right click on the game and mod directory is empty 
I am using Windows 10 portable version.

**Comment by amakvana** [comment]
SwitchEmuModDownloader currently doesn't support Ryujinx, as the codebase was based around Yuzu. However, I have a test build with Ryujinx semi-working.

Ryujinx handles mods slightly differently in terms of file layouts, etc. So just need to tweak and get it working smoothly and consistent

**Comment by OrdinaryCloverOC** [comment]
https://github.com/FennyFatal/RyuSAK might be relevant for the meantime. *alternatively this was forked from https://github.com/Ecks1337/RyuSAK
