### ISSUE TITLE
The software just does not find any games

### ISSUE THREAD

**Issue by TOTKSWITCHPIRATE** [amakvana/YuzuModDownloader#50]
The software just does not find any games

**To Reproduce**
1.  just press download game mods

**Expected behavior**

**Screenshots**
![Screenshot 2024-05-03 175021](https://github.com/amakvana/SwitchEmuModDownloader/assets/168754651/bd6da0af-a0b3-4341-9873-7449d79ee9b5)

**Desktop/Laptop (please complete the following information):**
 - OS: Windows 11,.]
 - Yuzu Version [1734]
 - Yuzu Installed
 - Game Title [TLOZ TOTK/ The legend of zelda: tears of the kingdom]
 - Game Title ID [0100F2C0115B6000 - found underneath the title in games list within Yuzu]
 - Path to `Mod Load Root` folder: C:\Users\billy\AppData\Roaming\yuzu\load\0100F2C0115B6000 idk what the folder is sorry

[qt-config.zip](https://github.com/amakvana/SwitchEmuModDownloader/files/15206577/qt-config.zip)

**Comment by TOTKSWITCHPIRATE** [comment]
help @amakvana

**Comment by TOTKSWITCHPIRATE** [comment]
pls help @amakvana

**Comment by amakvana** [comment]
Sorry about the delayed reply! Been away. 

Which Repo are you selecting before clicking the Download button? 

Also, I've tweaked your `qt-config.ini` file, download and test

[qt-config.zip](https://github.com/amakvana/SwitchEmuModDownloader/files/15287632/qt-config.zip)

**Comment by TOTKSWITCHPIRATE** [comment]
im using the alt repo and im trying the new file right now

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana the software still says this:
![Screenshot 2024-05-12 155324](https://github.com/amakvana/SwitchEmuModDownloader/assets/168754651/90901871-dc0f-42a6-b063-1f83bf16291b)

**Comment by amakvana** [comment]
Each repo contains different mods. 

For TOTK, select the "HolographicWings TOTK Repo" and try again. I've just tested it now and that repo works as expected. The downloads from this repo can be large, so you'll need to wait while the archive is being downloaded

**Comment by TOTKSWITCHPIRATE** [comment]
ok thx

**Comment by TOTKSWITCHPIRATE** [comment]
omg sorry @amakvana i know its very late in the uk but the software just crashes on the 2nd download

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana 

https://github.com/amakvana/SwitchEmuModDownloader/assets/168754651/f4d6af51-7e22-41b3-aa6c-8c8c2683e94a

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana ill see u in the morning!

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana it still is crashing when at the 2nd download

**Comment by TOTKSWITCHPIRATE** [comment]
lemme try again

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana now it just crashes at the secount i press download :[

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana when its trys to unpack it does this:

https://github.com/amakvana/SwitchEmuModDownloader/assets/168754651/fa57fe69-6c4d-45bb-b257-798db4c9655f

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana it still is not working

**Comment by amakvana** [comment]
Just had a look at the latest version of the TOTK mods, looks like they are now packaged inside an exe, rather than as separate zips. Let me see what I can do

**Comment by TOTKSWITCHPIRATE** [comment]
ok  thank you amak

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana i am going to breakfast so i wall see you in about 20 mins LMK when you have any more info!

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana i found this at https://github.com/hoverbike1/TOTK-Mods-collection/releases/tag/v4.20

![Screenshot 2024-05-13 104858](https://github.com/amakvana/SwitchEmuModDownloader/assets/168754651/3f0096b9-6a81-46b1-8597-26acdccde852)

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana hope it helps!

**Comment by amakvana** [comment]
Hi @TOTKSWITCHPIRATE,

Thanks for all the insights, help, etc.

Try the test build attached below and let me know the outcome. There's a bunch of fixes and tweaks, so let me know your thoughts. 

Extract the zip, place it where your yuzu.exe and rerun. 

Cheers!

[SwitchEmuModDownloader_1.5.2.0_TestBuild.zip](https://github.com/amakvana/SwitchEmuModDownloader/files/15297789/SwitchEmuModDownloader_1.5.2.0_TestBuild.zip)

**Comment by TOTKSWITCHPIRATE** [comment]
Okay Thank You Akash! 

Cheers!

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana um its still crashing

**Comment by TOTKSWITCHPIRATE** [comment]
wait

**Comment by TOTKSWITCHPIRATE** [comment]
1 sec

**Comment by TOTKSWITCHPIRATE** [comment]
@amakvana Thank you so much Akash It works now 
Cheers,

William

**Comment by amakvana** [comment]
> @amakvana um its still crashing 

It will hang slightly on the "extracting" portion because the archives are large in file size, but they do get processed.

**Comment by amakvana** [comment]
> @amakvana Thank you so much Akash It works now Cheers,
> 
> William

Thanks for confirming! For now, use the test build. 

Once I commit the changes to the repo, the test build will invalidate and the latest version will contain the fixes which the test build currently has

**Comment by TOTKSWITCHPIRATE** [comment]
wow it is  taking 4ever to launch

**Comment by TOTKSWITCHPIRATE** [comment]
CLOSE COMMENT
