### ISSUE TITLE
Always downloading 0 items

### ISSUE THREAD

**Issue by thethiny** [amakvana/YuzuModDownloader#7]
First of all, thanks for taking the time to develop this tool. I just wanted to try it to see what it does, but for some reason it doesn't download anything for me, always shows 0 mods downloaded. I tried placing it in Yuzu folder, in my NSP folder, Mod folder, and every place, yet it refused to download.

**Comment by amakvana** [comment]
Can I see some screenshots of your current setup? Along with the following details:

- Yuzu Installation Path
- YuzuModDownloader Path
- Antivirus? If so, which?
- Have you dumped the latest prod.keys?
- Has Yuzu been setup properly and can Yuzu see the games inside its own UI when loaded?

**Comment by thethiny** [comment]
My yuzu is in the default path, %appdata%.
Yuzu mod Downloader is in that same folder next to the exe.
No anti-virus. Windows defender.
Yes keys are working.
Yes yuzu is working perfectly.

**Comment by amakvana** [comment]
Ok, that seems normal! Strange! Have you also moved the .dll files that YuzuModDownloader comes with into the same directory as Yuzu too?

Are you able to confirm the path of your Mod Directory? To do this, see below:

Open yuzu.exe > Emulation > Configure > System > Filesystem

Then confirm the "Mod Load Root" path

**Comment by thethiny** [comment]
My mod directory is custom. It's under D:/YuzuMods.

**Comment by amakvana** [comment]
That will be why then, it only detects the default location and the portable location which is the "user" folder located in the same directory as yuzu.exe 

In the next update, I'll be looking to pull the location from the settings instead so custom paths are also supported

**Comment by thethiny** [comment]
To verify your theory, I created a HardLink from Yuzu\load to my Mods folder and now it is working perfectly.
